resources:
  repositories:
    - repository: test-public
      name: padget11/test-public
      endpoint: padget11
      type: github
      ref: refs/heads/main

stages:
  - stage: Build
    pool:
      name: Azure Pipelines
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
            fetchTags: false

          - script: |
              mkdir -p ~/.ssh
              echo "$(ssh-key)" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              npm install

          - task: Npm@1
            displayName: 'npm build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run --if-present build'

          - script: |
              rm -f ~/.ssh/id_rsa
              rm -rf ~/.ssh
            displayName: "Remove SSH Key"
            condition: always()